# Generated by Django 2.1.1 on 2018-09-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='number',
            field=models.IntegerField(default=0, verbose_name='番号'),
        ),
    ]
